# Generated by Django 5.2.4 on 2025-07-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='size',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
