# Generated by Django 5.2.4 on 2025-07-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_menu_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='brand',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
