# Generated by Django 5.2.4 on 2025-07-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_menu_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='recipe',
            new_name='product',
        ),
    ]
